#!/usr/bin/env python3
"""Regenerate the Understandings INDEX.md from the slug folders.

The index is a reference table (folder + description + trigger), never a copy of the
knowledge itself: an agent reads the index to decide which Understandings to load, then
reads only those folders.

Usage:
    python3 .agents/skills/ai-understanding/scripts/understanding_index.py [store-dir]

Defaults to `.context/understandings`. Pure standard library, read/write only, no network.
Exits 1 when a unit fails validation — the index is still written so the drift is visible.
"""

from __future__ import annotations

import sys
from pathlib import Path

DEFAULT_STORE = Path(".context/understandings")
UNIT_FILENAME = "UNDERSTANDING.md"
REQUIRED_FIELDS = ("slug", "description", "trigger", "scope", "confidence")
VALID_SCOPES = ("portable", "repo-specific")
VALID_CONFIDENCE = ("observed", "verified", "contested")


def parse_frontmatter(text: str) -> dict:
    """Parse the flat scalars, one level of nesting, and list values this format uses."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}

    data: dict = {}
    parent: str | None = None
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if not line.strip() or line.lstrip().startswith("#"):
            continue

        indented = line[:1].isspace()
        stripped = line.strip()

        if indented and parent:
            if stripped.startswith("- "):
                if not isinstance(data.get(parent), list):
                    data[parent] = []
                data[parent].append(stripped[2:].strip())
            elif ":" in stripped:
                key, _, value = stripped.partition(":")
                if not isinstance(data.get(parent), dict):
                    data[parent] = {}
                data[parent][key.strip()] = value.strip()
            continue

        if ":" not in stripped:
            continue
        key, _, value = stripped.partition(":")
        key = key.strip()
        value = value.strip()
        if value:
            data[key] = value
            parent = None
        else:
            data[key] = {}
            parent = key
    return data


def placeholder(value: str) -> bool:
    return value.startswith("<") and value.endswith(">")


def load_units(store: Path) -> tuple[list[dict], list[str]]:
    units: list[dict] = []
    problems: list[str] = []

    for folder in sorted(p for p in store.iterdir() if p.is_dir()):
        unit_file = folder / UNIT_FILENAME
        if not unit_file.is_file():
            problems.append(f"{folder.name}/ has no {UNIT_FILENAME}")
            continue

        fields = parse_frontmatter(unit_file.read_text(encoding="utf-8"))
        if not fields:
            problems.append(f"{folder.name}/{UNIT_FILENAME} has no frontmatter")
            continue

        for field in REQUIRED_FIELDS:
            value = fields.get(field)
            if not isinstance(value, str) or not value or placeholder(value):
                problems.append(f"{folder.name}: '{field}' is missing or still a placeholder")

        if fields.get("slug") not in (folder.name, None):
            problems.append(f"{folder.name}: slug '{fields['slug']}' does not match the folder name")
        if isinstance(fields.get("scope"), str) and fields["scope"] not in VALID_SCOPES:
            problems.append(f"{folder.name}: scope '{fields['scope']}' is not one of {VALID_SCOPES}")
        if isinstance(fields.get("confidence"), str) and fields["confidence"] not in VALID_CONFIDENCE:
            problems.append(
                f"{folder.name}: confidence '{fields['confidence']}' is not one of {VALID_CONFIDENCE}"
            )

        fields["folder"] = folder.name
        units.append(fields)

    problems.extend(dangling_links(units))
    return units, problems


def dangling_links(units: list[dict]) -> list[str]:
    known = {unit["folder"] for unit in units}
    dangling = []
    for unit in units:
        links = unit.get("links")
        if not isinstance(links, list):
            continue
        for link in links:
            target = link.strip().strip("[]")
            if target and not placeholder(target) and target not in known:
                dangling.append(f"{unit['folder']}: link [[{target}]] has no matching folder")
    return dangling


def cell(value) -> str:
    if not isinstance(value, str) or not value:
        return "—"
    return value.replace("|", "\\|")


def render(units: list[dict]) -> str:
    lines = [
        "# Understandings — INDEX",
        "",
        "Generated by `.agents/skills/ai-understanding/scripts/understanding_index.py`. Do not hand-edit.",
        "",
        "Each row references a folder; the knowledge lives in that folder's `UNDERSTANDING.md`.",
        "Match a **trigger** against the task at hand, then read only the folders that matched.",
        "",
    ]

    if not units:
        lines += ["_No Understandings encoded yet._", ""]
        return "\n".join(lines)

    lines += [
        "| Folder | Description | Trigger | Scope | Confidence | Updated |",
        "|--------|-------------|---------|-------|------------|---------|",
    ]
    for unit in units:
        folder = unit["folder"]
        lines.append(
            f"| [`{folder}/`](./{folder}/) | {cell(unit.get('description'))} "
            f"| {cell(unit.get('trigger'))} | {cell(unit.get('scope'))} "
            f"| {cell(unit.get('confidence'))} | {cell(unit.get('updated'))} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    store = Path(argv[1]) if len(argv) > 1 else DEFAULT_STORE
    if not store.is_dir():
        print(f"store not found: {store}", file=sys.stderr)
        return 2

    units, problems = load_units(store)
    (store / "INDEX.md").write_text(render(units), encoding="utf-8")
    print(f"indexed {len(units)} understanding(s) -> {store / 'INDEX.md'}")

    for problem in problems:
        print(f"  problem: {problem}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
